"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ADD_DICTIONARY = exports.SET_DICTIONARIES = exports.SET_LANGUAGES = exports.SET_CURRENT_LANGUAGE = void 0;
var SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
exports.SET_CURRENT_LANGUAGE = SET_CURRENT_LANGUAGE;
var SET_LANGUAGES = 'SET_LANGUAGES';
exports.SET_LANGUAGES = SET_LANGUAGES;
var SET_DICTIONARIES = 'SET_DICTIONARIES';
exports.SET_DICTIONARIES = SET_DICTIONARIES;
var ADD_DICTIONARY = 'ADD_DICTIONARY';
exports.ADD_DICTIONARY = ADD_DICTIONARY;