export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE'
export const SET_LANGUAGES = 'SET_LANGUAGES'
export const SET_DICTIONARIES = 'SET_DICTIONARIES'
export const ADD_DICTIONARY = 'ADD_DICTIONARY'